### ISSUE TITLE
Dont know any other way to get through to you, i know you are busy

### ISSUE THREAD

**Issue by LGCMcLovin** [slimshadeey1/Homework#25]
Dont be a stranger man, im sorry if i upset you, i lost a lot of staff the same time you disappeared again, but a lot of people miss you. ive been forming a group to work on the smite project, Connor is one from the powered rails project, another is the SkillAPI plugin Developer, and one who made a plugin called Aappartments, misspelled but cool plugin. 

i know you may be too busy to help out with anything, or you may not even have interest in helping me anymore thats fine. but last i checked we were still friends. so dont be a stranger man.

**Comment by slimshadeey1** [comment]
Oh shibby, I never even saw this!

**Comment by slimshadeey1** [comment]
Lets talk on skype

**Comment by Phasesaber** [comment]
shibby shibby
